// Derives a short, human-readable "what is this agent working on" label from a
// session transcript's user messages. The newest genuine user prompt wins.
//
// Transcripts are messy: tool results arrive as `type:"user"` records, slash
// commands and local-command output are injected as user messages, and subagent
// prompts appear as sidechain entries. We filter all of those out and keep only
// text the human actually typed, then shorten it into a label.

const GOAL_MAX_LENGTH = 40;

// Leading conversational filler stripped off the front of a prompt, longest-first
// so multi-word phrases match before their shorter prefixes.
const FILLER_PHRASES = [
  "i would like you to", "i'd like you to", "i want you to",
  "i would like to", "i'd like to", "i want to",
  "i need you to", "i need to", "we need to",
  "can you please", "could you please", "would you please",
  "go ahead and", "help me",
  "can you", "could you", "would you", "will you",
  "let's", "lets",
  "please", "pls", "plz",
  "okay", "ok", "so", "hey", "hi", "hello", "yo", "alright",
  "now", "actually", "just", "also", "then", "um", "uh",
].sort((a, b) => b.length - a.length);

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

// Matches a filler phrase at the start, but only when it's a whole word (not the
// prefix of a longer word — so "so" never eats "sort").
const FILLER_RE = new RegExp(
  `^(?:${FILLER_PHRASES.map(escapeRegex).join("|")})(?![a-zA-Z])`,
  "i",
);

const LEADING_SEPARATORS_RE = /^[\s,:;.!?–—-]+/;

/** Pull the human-typed text out of a transcript user record, or null if this
 *  record isn't a genuine prompt (tool result, meta, slash command, sidechain…). */
export function extractUserPromptText(record: Record<string, unknown>): string | null {
  if (record.isMeta === true || record.isSidechain === true) return null;

  const message = record.message as Record<string, unknown> | undefined;
  const content = message?.content;

  let text: string;
  if (typeof content === "string") {
    text = content;
  } else if (Array.isArray(content)) {
    const blocks = content as Array<Record<string, unknown>>;
    // A tool_result block means this "user" record is really a tool response.
    if (blocks.some((b) => b.type === "tool_result")) return null;
    text = blocks
      .filter((b) => b.type === "text" && typeof b.text === "string")
      .map((b) => (b.text as string).trim())
      .filter((s) => s.length > 0)
      .join("\n");
  } else {
    return null;
  }

  // Drop injected system-reminder blocks that ride along with real prompts.
  text = text.replace(/<system-reminder>[\s\S]*?<\/system-reminder>/gi, "").trim();
  if (!text) return null;

  // Slash commands, local command output, and caveat banners aren't user intent.
  if (/^<command-(name|message|args)>/i.test(text)) return null;
  if (/^<local-command-(stdout|stderr)>/i.test(text)) return null;
  if (/^Caveat: The messages below were generated by the user while running/i.test(text)) return null;

  return text;
}

/** Shorten a raw prompt into a concise goal label. May return "" if nothing
 *  meaningful remains after stripping filler. */
export function cleanGoal(raw: string, maxLen = GOAL_MAX_LENGTH): string {
  let s = (raw || "")
    .split("\n")
    .map((line) => line.trim())
    .find((line) => line.length > 0) ?? "";

  // Peel leading filler + separators until the prompt's verb/subject is at the front.
  let changed = true;
  while (changed) {
    changed = false;
    s = s.replace(LEADING_SEPARATORS_RE, "");
    const m = FILLER_RE.exec(s);
    if (m) {
      s = s.slice(m[0].length);
      changed = true;
    }
  }
  s = s.replace(LEADING_SEPARATORS_RE, "").trim();

  if (s.length > maxLen) {
    const cut = s.slice(0, maxLen);
    const lastSpace = cut.lastIndexOf(" ");
    s = (lastSpace > maxLen * 0.6 ? cut.slice(0, lastSpace) : cut).trimEnd() + "…";
  }
  return s;
}

/** Convenience: extract + clean a user record into a goal label, or null. */
export function deriveGoal(record: Record<string, unknown>): string | null {
  const text = extractUserPromptText(record);
  if (text === null) return null;
  const goal = cleanGoal(text);
  return goal.length > 0 ? goal : null;
}
