import { describe, it, expect } from "vitest";
import { extractUserPromptText, cleanGoal, deriveGoal } from "../goalExtraction.js";

function userRecord(content: unknown, extra: Record<string, unknown> = {}) {
  return { type: "user", message: { content }, ...extra };
}

describe("extractUserPromptText", () => {
  it("returns plain string content", () => {
    expect(extractUserPromptText(userRecord("add a login form"))).toBe("add a login form");
  });

  it("joins text blocks in array content", () => {
    const rec = userRecord([
      { type: "text", text: "add a login form" },
      { type: "text", text: "with validation" },
    ]);
    expect(extractUserPromptText(rec)).toBe("add a login form\nwith validation");
  });

  it("returns null for tool_result turns (synthetic user messages)", () => {
    const rec = userRecord([
      { type: "tool_result", tool_use_id: "abc", content: "ok" },
    ]);
    expect(extractUserPromptText(rec)).toBeNull();
  });

  it("returns null for meta messages", () => {
    expect(extractUserPromptText(userRecord("local command output", { isMeta: true }))).toBeNull();
  });

  it("returns null for sidechain (subagent) prompts", () => {
    expect(extractUserPromptText(userRecord("you are a subagent", { isSidechain: true }))).toBeNull();
  });

  it("returns null for slash-command invocations", () => {
    const rec = userRecord("<command-name>/clear</command-name>\n<command-message>clear</command-message>");
    expect(extractUserPromptText(rec)).toBeNull();
  });

  it("returns null for caveat wrappers", () => {
    const rec = userRecord("Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these.");
    expect(extractUserPromptText(rec)).toBeNull();
  });

  it("returns null for local-command-stdout", () => {
    expect(extractUserPromptText(userRecord("<local-command-stdout>npm ok</local-command-stdout>"))).toBeNull();
  });

  it("strips trailing system-reminder blocks from a real prompt", () => {
    const rec = userRecord("add dark mode\n<system-reminder>ignore me</system-reminder>");
    expect(extractUserPromptText(rec)).toBe("add dark mode");
  });

  it("returns null when content is missing or empty", () => {
    expect(extractUserPromptText(userRecord(""))).toBeNull();
    expect(extractUserPromptText({ type: "user" })).toBeNull();
  });
});

describe("cleanGoal", () => {
  it("strips leading filler phrases", () => {
    expect(cleanGoal("Please fix the ping-pong slot positions")).toBe("fix the ping-pong slot positions");
  });

  it("strips stacked filler", () => {
    const out = cleanGoal("ok so i want to add a chess set to the lounge where two idle agents play");
    expect(out.startsWith("add a chess set")).toBe(true);
    expect(out).not.toContain("i want to");
  });

  it("strips the example 'now ...' opener", () => {
    expect(cleanGoal("now fix the ping-pong slot positions")).toBe("fix the ping-pong slot positions");
  });

  it("strips 'can you' question openers but keeps the rest", () => {
    expect(cleanGoal("Can you refactor the auth module?")).toBe("refactor the auth module?");
  });

  it("does not strip filler that is only a word prefix", () => {
    expect(cleanGoal("sort the list alphabetically")).toBe("sort the list alphabetically");
  });

  it("uses only the first non-empty line", () => {
    expect(cleanGoal("add dark mode\n\nalso make it pretty")).toBe("add dark mode");
  });

  it("truncates long goals on a word boundary with an ellipsis", () => {
    const out = cleanGoal("add a chess set to the lounge where two idle agents pair up and play");
    expect(out.startsWith("add a chess set")).toBe(true);
    expect(out.endsWith("…")).toBe(true);
    expect(out.length).toBeLessThanOrEqual(41);
  });

  it("returns empty string when nothing is left after cleaning", () => {
    expect(cleanGoal("ok please")).toBe("");
    expect(cleanGoal("   ")).toBe("");
  });
});

describe("deriveGoal", () => {
  it("extracts and cleans in one step", () => {
    expect(deriveGoal(userRecord("ok please add login"))).toBe("add login");
  });

  it("returns null for non-prompt records", () => {
    expect(deriveGoal(userRecord([{ type: "tool_result", tool_use_id: "x" }]))).toBeNull();
  });

  it("returns null when the cleaned goal is empty", () => {
    expect(deriveGoal(userRecord("ok so"))).toBeNull();
  });
});
